apiVersion: v1
kind: Service
metadata:
  name: contract
  labels:
    etechpro: microservices
    app: contract
spec:
  ports:
    - port: 8011
      targetPort: http
  selector:
    app: contract
  type: LoadBalancer