pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                sh '''
                  git version
                  buildctl --version
                  kubectl version --short
                  helm version --short
                '''
            }
        }
        stage('Build') {
            steps {
              echo "Building image tag: ${REGISTRY_SERVER}/${REGISTRY_USER}/contract:${BUILD_NUMBER}-kiamol"
              dir ('contract') {
                sh 'chmod +x ci/build.sh && ./ci/build.sh'
              }
            }
        }
        stage('Run') {
            steps {
              echo "Deploying to test"
              dir ('contract') {
                sh 'chmod +x ci/run.sh && ./ci/run.sh'
              }
            }
        }
    }
}