apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: contract
    app.kubernetes.io/instance: {{ .Release.Name }}
    etechpro: microservices
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: contract
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: contract
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: contract
          image: {{ .Values.registryServer }}/{{ .Values.registryUser }}/contract:{{ .Values.imageBuildNumber }}-kiamol 
          imagePullPolicy: Always    
          ports:
            - name: http
              containerPort: 8080  
      imagePullSecrets:
      - name: {{ .Values.registrySecretName }}